name: publish_website

on:
  push:
    branches:
      - main

jobs:
    push_to_branch:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                fetch-depth: 0
            
            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.x'
            
            - name: Install Jupyter
              run: pip install notebook

            - name: Export the notebook and Add files
              run: |
                mkdir temp
                cp -r img/ temp/img/
                jupyter nbconvert tutorial.ipynb --to slides --reveal-prefix reveal.js --output temp/index.html
                ls -R temp

            - name: Deploy
              uses: s0/git-publish-subdir-action@develop
              env:
                REPO: self
                BRANCH: website
                FOLDER: temp
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                

